### ISSUE TITLE
Empty files created with candidate name and company does not complete

### ISSUE THREAD

**Issue by KaratasFurkan** [johannes-mueller/company-wordfreq.el#1]
Hi, I tried your package with emacs 28.0.50 but could not get the completions. Some empty files created with candidate names, instead.

Here is a screenshot of my config and .emacs.d directory:
![Screenshot_20210127_184624](https://user-images.githubusercontent.com/29731420/106015912-ff245500-60cf-11eb-9bce-827c197fd95c.png)

**Comment by johannes-mueller** [comment]
Huh, thats odd. Thanks for the report.

I have just tried with emacs 28.0.50 but I don't observe what you describe, here it works smoothly. I could not find any explanation for that behavior now. Maybe the external command to grep into the word list file is misbehaving on your system.

Can you provide the following information

* ripgrep version
* system infomation (OS, Distro, Version, Architecture)
* Where do these strange empty files appear? Always in `~/.emacs.d` or in the current working directory?

Thanks for your help

**Comment by KaratasFurkan** [comment]
- ripgrep version: **12.1.1**
- OS: **Manjaro 20.2 Nibia**
- Always in ~/.emacs.d

I will try with emacs -Q soon.
