### ISSUE TITLE
On Ubuntu 20.04, `company-wordfreq.el` failed to suggest possible words for writting.

### ISSUE THREAD

**Issue by hongyi-zhao** [johannes-mueller/company-wordfreq.el#5]
On Ubuntu 20.04, I try the suggested method given by you [here](https://github.com/johannes-mueller/company-wordfreq.el#configuration) and the method represented [here](https://md-arif-shaikh.github.io/2021/05/27/typing-bangla-in-emacs.html). But none of them worked on my case in my environment. See my following init file, `~/.emacs.d/init.company-wordfreq.el`, used for the testing:

```emacs-lisp
;;Bootstrap straight
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)

(straight-use-package
 '(company-wordfreq :type git :host github :repo "johannes-mueller/company-wordfreq.el"))
 

; Method 1, based on the method describe at:
;https://md-arif-shaikh.github.io/2021/05/27/typing-bangla-in-emacs.html
(defun remove-quail-show-guidance ()
  nil)
(defun remove-quail-completion ()
  (quail-select-current))
(defun en-company-wordfreq ()
  (interactive)
  (advice-add 'quail-show-guidance :override #'remove-quail-show-guidance)
  (advice-add 'quail-completion :override #'remove-quail-completion)
  (setq ispell-local-dictionary "english")
  (setq-local company-backends '(company-wordfreq))
  (setq-local company-transformers nil))

; Method 2, based on your official guidance:
;(setq ispell-local-dictionary "english")  
;(add-hook 'text-mode-hook (lambda ()
;                            (setq-local company-backends '(company-wordfreq))
;                            (setq-local company-transformers nil)))
```

The dictionary file used for my testing:

```bash
$ wc -l ~/.emacs.d/wordfreq-dicts/english.txt 
50000 /home/werner/.emacs.d/wordfreq-dicts/english.txt
```

Start Emacs with the following command:

`$ emacs -q --load ~/.emacs.d/init.company-wordfreq.el`

The testing workflow is described below according to the notes [here](https://md-arif-shaikh.github.io/2021/05/27/typing-bangla-in-emacs.html):

1. Change the input-method to `british` using `C-\`
2. Enable `company-wordfreq` and other changes for a nice experience using `M-x en-company-wordfreq`
3. `TAB` to get suggestions.
4. `ARROW` to select one.

But it doesn't work at all.

Any hints for this problem?

Regards,
HY

**Comment by johannes-mueller** [comment]
You need to enable `company-mode` at some point. Probably easiest with `(add-hook 'after-init-hook 'global-company-mode)`. See the company page for details on `company.el` (https://company-mode.github.io/)

When I run a plain emacs27.2 installation only with your init file and I manually enable `company-mode`, it works smoothly.

**Comment by hongyi-zhao** [comment]
The better solution are given by [KaratasFurkan](https://github.com/KaratasFurkan) [here](https://github.com/KaratasFurkan/.emacs.d/issues/1#issuecomment-864426970). 

Thank you again.
