### ISSUE TITLE
Please use a license that is compatible with Emacs' GPL-3.0-or-later

### ISSUE THREAD

**Issue by tarsius** [johannes-mueller/company-wordfreq.el#6]
`GPL-2.0-only` is not compatible with the license used by Emacs, `GPL-3.0-or-later`. To allow us to continue to distribute this package on Melpa, you would have to update to something like `GPL-3.0-only` or `GPL-2.0-or-later`.

Please update both the `LICENSE` file (or similar) and update/add a library header specifying the same license like:

```elisp
;; SPDX-License-Identifier: GPL-3.0-or-later
```

/cc @riscy

**Comment by johannes-mueller** [comment]
Does it now suite the requirements of MELPA?

**Comment by tarsius** [comment]
Yes. Thanks a lot!
